[package]
name = "nx"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2018"

[dependencies.linked_list_allocator]
version = "0.8.4"

[dependencies.paste]
version = "1.0"

[dependencies.arrayvec]
version = "0.5.1"
default-features = false
features = []