[package]
name = "nx"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked_list_allocator = "0.8.4"
enumflags2 = "^0.6"